baseURL = 'https://zerokinetik.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
[markup.highlight]
noclasses = false
style = "github"
[[module.imports]]
path = "github.com/willfaught/paige"
