baseURL = 'https://ZeroKinetik.github.io'
languageCode = 'en-us'
title = 'Heman sakkthivel'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'base16-cupcake'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a CS student figuring things out. I am interested in a various topics, including algorithms, distributed systems, database management and software design principles.
Feel free to read [about myself](/about) or take a look at my [posts](/posts).
"""


# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

showFooter = false


# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/hemansakkthivelms14"

[[params.social]]
name = "github"
url = "https://github.com/ZeroKinetik"

# Main menu pages

[[params.menu]]
name = "~"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'catppuccin-frappe'

[params.giscus]
enable = false
repo = "your/repo"
repoid = "id"
category = "category"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme" 


[caches]
  [caches.images]
    dir = ':cacheDir/images'